### ISSUE TITLE
libcurl

### ISSUE THREAD

**Issue by xsellier** [Pintea/tiniest-analytics#4]
Hey,

Thank you for that lib. Im trying to use it, however Im having trouble compiling libcurl for godot.
May you share a bit of your godot repository in order to be able to compile libcurl + godot together.

I used those prebuilt binaries:
https://github.com/djp952/prebuilt-libcurl-nossl

This is the git repository I forked from yours:
https://github.com/binogure-studio/tiniest-analytics

Thanks!

**Comment by Pintea** [comment]
Hi,Never used godot engine, but I assume you're using visual studio? Which version?You need to compile libcurl using your version of visual studio. In their source package (libcurl/projects/windows) they have a visual studio .sln file which you can use to compile libcurl into a .lib.
I built it without SSL and I added CURL_DISABLE_LDAP to the preprocessor.
Let me know if it works.
-Mihai

    On Thursday, December 6, 2018, 12:50:40 AM GMT+2, Xavier Sellier <notifications@github.com> wrote:  
 
 
Hey,

Thank you for that lib. Im trying to use it, however Im having trouble compiling libcurl for godot.
May you share a bit of your godot repository in order to be able to compile libcurl + godot together.

Thanks!
